# See https://github.com/bbatsov/rubocop/blob/master/config/default.yml for doc
# See https://github.com/bbatsov/rubocop/blob/master/config for enabled/disabled
# See http://rubocop.readthedocs.io/en/latest for reference documentation

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'bin/*'

Layout:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Lint/Debugger:
  Enabled: true
  Severity: error

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true

# Defining a method with parameters needs parentheses.
Style/MethodDefParentheses:
  Enabled: true

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

# Rewrite unless..else as if..else with positive case first
Style/UnlessElse:
  Enabled: true
  StyleGuide: '#no-else-with-unless'

Style/IfInsideElse:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

# No empty parenthesis
Style/DefWithParentheses:
  Enabled: true
Style/DoubleNegation:
  Enabled: true
Style/EmptyLambdaParameter:
  Enabled: true
Style/MethodCallWithoutArgsParentheses:
  Enabled: true

# Use quotes for string literals when they are enough.
Style/RedundantPercentQ:
  Enabled: true

Style/StringLiterals:
  Enabled: true

# No trailing comma in argument lists, Array or Has
Style/TrailingCommaInArguments:
  Enabled: true
Style/TrailingCommaInArrayLiteral:
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Enabled: true

# Use my_method(my_arg) not my_method( my_arg ) or my_method my_arg.
Lint/RequireParentheses:
  Enabled: true

# Inherit from StandardError or RuntimeError, not Exception
Lint/InheritException:
  Enabled: true

# Do not rescue Exception, rescue StandardError or specific errors (better)
Lint/RescueException:
  Enabled: true

Lint/RescueType:
  Enabled: true

Lint/ShadowedException:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodParameterName:
  Enabled: true

Naming/VariableName:
  Enabled: true
  Severity: warning
